"""Changed Models

Revision ID: 2e14bb3c2284
Revises: 9b2d1c8a4f03
Create Date: 2026-09-28 10:39:08.709507

"""
from typing import Sequence, Union
import sqlmodel.sql.sqltypes
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e14bb3c2284'
down_revision: Union[str, Sequence[str], None] = '9b2d1c8a4f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('subscription_status', sa.Enum('trialing', 'active', 'past_due', 'canceled', 'unpaid', name='subscription_status', native_enum=False), nullable=False))
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.drop_column('organizations', 'is_active')
    op.add_column('refresh_tokens', sa.Column('revoked_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.drop_column('refresh_tokens', 'is_revoked')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('users', 'is_verified')
    op.add_column('refresh_tokens', sa.Column('is_revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'revoked_at')
    op.add_column('organizations', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_column('organizations', 'subscription_status')
    # ### end Alembic commands ###
